-- ============================================================
-- SmartCart — Seed Data (Mock Data)
-- ============================================================
-- Maintained by the DB team. Full INSERT statements are in backend/docs/insert_mockdata.sql
-- Includes: retailers (3), categories (8), brands (17), units (6),
--           products (17), product_variants (51), price_records (408),
--           scrape_jobs (24), users (5), shopping_lists (8),
--           list_items (40), price_alerts (8), todos (6),
--           inventory_items (32), seasonal_patterns (7)
-- ============================================================

-- TODO: DB team to provide the complete seed data script
